### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DaRandomCube**
since `linux-xanmod-anbox` and `linux-xanmod-anbox-header` got deleted from chaotic aur, i've updated the readme so the project will be usable

i know i know, my english is bad

### CODE REVIEW

**Comment by nitanmarcel** [comment]
Btw I've seen the xanmod kernel here, doesn't this work?

https://aur.archlinux.org/packages/linux-xanmod

**Comment by DaRandomCube** [comment]
in the readme you said linux-xanmod-anbox, not the stock linux-xanmod
i will test that later (waydroid-magisk didn't work even with xanmod-anbox, only waydroid-script worked)

**Comment by nitanmarcel** [comment]
Ah right. My bad sorry I forgot about the modules

**Comment by DaRandomCube** [comment]
> in the readme you said linux-xanmod-anbox, not the stock linux-xanmod i will test that later (waydroid-magisk didn't work even with xanmod-anbox, only waydroid-script worked)

when I run `sudo waydroid_magisk setup` it prints `lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "su"` , `linux-xanmod-anbox` was supposed to fix that according to pinned issue

**Comment by TheEssem** [comment]
Having the same issue that this is describing, running a custom linux-tkg kernel build that has the same config options that `linux-xanmod-anbox` uses.

Interestingly, a look at the logcat seems to indicate that the `magisk64` binary is crashing on startup:
```
11-03 14:21:10.187     0     0 I init    : processing action (post-fs-data) from (/system/etc/init/bootanim.rc:12)
11-03 14:21:10.187     0     0 I init    : starting service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)'...
11-03 14:21:10.187     0     0 E libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
11-03 14:21:10.187     0     0 E init    : createProcessGroup(0, 58) failed for service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)': Read-only file system
11-03 14:21:10.187     0     0 I init    : SVC_EXEC service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' pid 58 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
11-03 14:21:10.217     0     0 I init    : Service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 58) exited with status 0 waiting took 0.029000 seconds
11-03 14:21:10.217     0     0 I init    : Sending signal 9 to service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 58) process group...
11-03 14:21:10.217     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 58 in 0ms
11-03 14:21:10.217     0     0 I init    : starting service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)'...
11-03 14:21:10.217     0     0 E libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
11-03 14:21:10.217     0     0 E init    : createProcessGroup(0, 59) failed for service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)': Read-only file system
11-03 14:21:10.217     0     0 I init    : SVC_EXEC service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' pid 59 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
11-03 14:21:10.220     0     0 I init    : Service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 59) exited with status 1 waiting took 0.002000 seconds
11-03 14:21:10.220     0     0 I init    : Sending signal 9 to service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 59) process group...
11-03 14:21:10.220     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 59 in 0ms
11-03 14:21:10.220     0     0 I init    : Command 'copy /system/etc/init/magisk/config /sbin/.magisk/config' action=post-fs-data (/system/etc/init/bootanim.rc:19) took 0ms and failed: Could not read input file '/system/etc/init/magisk/config': open() failed: No such file or directory
11-03 14:21:10.220     0     0 I init    : Command 'rm /dev/.magisk_unblock' action=post-fs-data (/system/etc/init/bootanim.rc:20) took 0ms and failed: unlink() failed: No such file or directory
11-03 14:21:10.220     0     0 I init    : starting service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)'...
11-03 14:21:10.221     0     0 E libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
11-03 14:21:10.221     0     0 E init    : createProcessGroup(0, 60) failed for service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)': Read-only file system
11-03 14:21:10.221     0     0 I init    : SVC_EXEC service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)' pid 60 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
11-03 14:21:10.245     0     0 E DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-03 14:21:10.245     0     0 E DEBUG   : LineageOS Version: '18.1-20231028-VANILLA-waydroid_x86_64'
11-03 14:21:10.245     0     0 E DEBUG   : Build fingerprint: 'waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/59:userdebug/test-keys'
11-03 14:21:10.245     0     0 E DEBUG   : Revision: '0'
11-03 14:21:10.245     0     0 E DEBUG   : ABI: 'x86_64'
11-03 14:21:10.245     0     0 E DEBUG   : Timestamp: 2023-11-03 19:21:10+0000
11-03 14:21:10.245     0     0 E DEBUG   : pid: 62, tid: 62, name: magiskd  >>> magiskd <<<
11-03 14:21:10.245     0     0 E DEBUG   : uid: 0
11-03 14:21:10.245     0     0 E DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-03 14:21:10.245     0     0 E DEBUG   : Abort message: 'stack corruption detected (-fstack-protector)'
11-03 14:21:10.245     0     0 E DEBUG   : rax 0000000000000000  rbx 000000000000003e  rcx 00007f68d4f5d758  rdx 0000000000000006
11-03 14:21:10.245     0     0 E DEBUG   : r8  0000000000000002  r9  0000000000000002  r10 00007ffccd350060  r11 0000000000000246
11-03 14:21:10.245     0     0 E DEBUG   : r12 0000000c00000000  r13 0000000000000000  r14 00007ffccd350058  r15 000000000000003e
11-03 14:21:10.245     0     0 E DEBUG   : rdi 000000000000003e  rsi 000000000000003e
11-03 14:21:10.245     0     0 E DEBUG   : rbp 000000000000000a  rsp 00007ffccd350048  rip 00007f68d4f5d758
11-03 14:21:10.246     0     0 E DEBUG   :  
11-03 14:21:10.246     0     0 E DEBUG   : backtrace:
11-03 14:21:10.246     0     0 E DEBUG   : #00 pc 000000000009d758  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+24) (BuildId: 082396c74061b06f8ce2a645b3a60e84)
11-03 14:21:10.246     0     0 E DEBUG   : #01 pc 00000000000a06c2  /apex/com.android.runtime/lib64/bionic/libc.so (abort+194) (BuildId: 082396c74061b06f8ce2a645b3a60e84)
11-03 14:21:10.246     0     0 E DEBUG   : #02 pc 00000000000b5433  /apex/com.android.runtime/lib64/bionic/libc.so (__stack_chk_fail+19) (BuildId: 082396c74061b06f8ce2a645b3a60e84)
11-03 14:21:10.246     0     0 E DEBUG   : #03 pc 0000000000021280  /sbin/magisk64 (BuildId: b05097c33460eef1651d47347bea416f9347b99e)
11-03 14:21:10.246     0     0 E DEBUG   : #04 pc 0000000000021374  /sbin/magisk64 (BuildId: b05097c33460eef1651d47347bea416f9347b99e)
11-03 14:21:10.246     0     0 E DEBUG   : #05 pc 0000000000020c88  /sbin/magisk64 (BuildId: b05097c33460eef1651d47347bea416f9347b99e)
11-03 14:21:10.246     0     0 E DEBUG   : #06 pc 000000000001eacd  /sbin/magisk64 (BuildId: b05097c33460eef1651d47347bea416f9347b99e)
11-03 14:21:10.246     0     0 E DEBUG   : #07 pc 0000000000093c88  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: 082396c74061b06f8ce2a645b3a60e84)
11-03 14:21:10.322     0     0 I init    : Untracked pid 62 received signal 6
11-03 14:21:10.322     0     0 I init    : Service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)' (pid 60) exited with status 0 waiting took 0.101000 seconds
11-03 14:21:10.322     0     0 I init    : Sending signal 9 to service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)' (pid 60) process group...
11-03 14:21:10.322     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 60 in 0ms
```

**Comment by nitanmarcel** [comment]
> Having the same issue that this is describing, running a custom linux-tkg kernel build that has the same config options that `linux-xanmod-anbox` uses.
> 
> Interestingly, a look at the logcat seems to indicate that the `magisk64` binary is crashing on startup:
> 
> ```
> 11-03 14:21:10.187     0     0 I init    : processing action (post-fs-data) from (/system/etc/init/bootanim.rc:12)
> 11-03 14:21:10.187     0     0 I init    : starting service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)'...
> 11-03 14:21:10.187     0     0 E libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
> 11-03 14:21:10.187     0     0 E init    : createProcessGroup(0, 58) failed for service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)': Read-only file system
> 11-03 14:21:10.187     0     0 I init    : SVC_EXEC service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' pid 58 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
> 11-03 14:21:10.217     0     0 I init    : Service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 58) exited with status 0 waiting took 0.029000 seconds
> 11-03 14:21:10.217     0     0 I init    : Sending signal 9 to service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 58) process group...
> 11-03 14:21:10.217     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 58 in 0ms
> 11-03 14:21:10.217     0     0 I init    : starting service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)'...
> 11-03 14:21:10.217     0     0 E libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
> 11-03 14:21:10.217     0     0 E init    : createProcessGroup(0, 59) failed for service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)': Read-only file system
> 11-03 14:21:10.217     0     0 I init    : SVC_EXEC service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' pid 59 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
> 11-03 14:21:10.220     0     0 I init    : Service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 59) exited with status 1 waiting took 0.002000 seconds
> 11-03 14:21:10.220     0     0 I init    : Sending signal 9 to service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 59) process group...
> 11-03 14:21:10.220     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 59 in 0ms
> 11-03 14:21:10.220     0     0 I init    : Command 'copy /system/etc/init/magisk/config /sbin/.magisk/config' action=post-fs-data (/system/etc/init/bootanim.rc:19) took 0ms and failed: Could not read input file '/system/etc/init/magisk/config': open() failed: No such file or directory
> 11-03 14:21:10.220     0     0 I init    : Command 'rm /dev/.magisk_unblock' action=post-fs-data (/system/etc/init/bootanim.rc:20) took 0ms and failed: unlink() failed: No such file or directory
> 11-03 14:21:10.220     0     0 I init    : starting service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)'...
> 11-03 14:21:10.221     0     0 E libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
> 11-03 14:21:10.221     0     0 E init    : createProcessGroup(0, 60) failed for service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)': Read-only file system
> 11-03 14:21:10.221     0     0 I init    : SVC_EXEC service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)' pid 60 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
> 11-03 14:21:10.245     0     0 E DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 11-03 14:21:10.245     0     0 E DEBUG   : LineageOS Version: '18.1-20231028-VANILLA-waydroid_x86_64'
> 11-03 14:21:10.245     0     0 E DEBUG   : Build fingerprint: 'waydroid/lineage_waydroid_x86_64/waydroid_x86_64:11/RQ3A.211001.001/59:userdebug/test-keys'
> 11-03 14:21:10.245     0     0 E DEBUG   : Revision: '0'
> 11-03 14:21:10.245     0     0 E DEBUG   : ABI: 'x86_64'
> 11-03 14:21:10.245     0     0 E DEBUG   : Timestamp: 2023-11-03 19:21:10+0000
> 11-03 14:21:10.245     0     0 E DEBUG   : pid: 62, tid: 62, name: magiskd  >>> magiskd <<<
> 11-03 14:21:10.245     0     0 E DEBUG   : uid: 0
> 11-03 14:21:10.245     0     0 E DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
> 11-03 14:21:10.245     0     0 E DEBUG   : Abort message: 'stack corruption detected (-fstack-protector)'
> 11-03 14:21:10.245     0     0 E DEBUG   : rax 0000000000000000  rbx 000000000000003e  rcx 00007f68d4f5d758  rdx 0000000000000006
> 11-03 14:21:10.245     0     0 E DEBUG   : r8  0000000000000002  r9  0000000000000002  r10 00007ffccd350060  r11 0000000000000246
> 11-03 14:21:10.245     0     0 E DEBUG   : r12 0000000c00000000  r13 0000000000000000  r14 00007ffccd350058  r15 000000000000003e
> 11-03 14:21:10.245     0     0 E DEBUG   : rdi 000000000000003e  rsi 000000000000003e
> 11-03 14:21:10.245     0     0 E DEBUG   : rbp 000000000000000a  rsp 00007ffccd350048  rip 00007f68d4f5d758
> 11-03 14:21:10.246     0     0 E DEBUG   :  
> 11-03 14:21:10.246     0     0 E DEBUG   : backtrace:
> 11-03 14:21:10.246     0     0 E DEBUG   : #00 pc 000000000009d758  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+24) (BuildId: 082396c74061b06f8ce2a645b3a60e84)
> 11-03 14:21:10.246     0     0 E DEBUG   : #01 pc 00000000000a06c2  /apex/com.android.runtime/lib64/bionic/libc.so (abort+194) (BuildId: 082396c74061b06f8ce2a645b3a60e84)
> 11-03 14:21:10.246     0     0 E DEBUG   : #02 pc 00000000000b5433  /apex/com.android.runtime/lib64/bionic/libc.so (__stack_chk_fail+19) (BuildId: 082396c74061b06f8ce2a645b3a60e84)
> 11-03 14:21:10.246     0     0 E DEBUG   : #03 pc 0000000000021280  /sbin/magisk64 (BuildId: b05097c33460eef1651d47347bea416f9347b99e)
> 11-03 14:21:10.246     0     0 E DEBUG   : #04 pc 0000000000021374  /sbin/magisk64 (BuildId: b05097c33460eef1651d47347bea416f9347b99e)
> 11-03 14:21:10.246     0     0 E DEBUG   : #05 pc 0000000000020c88  /sbin/magisk64 (BuildId: b05097c33460eef1651d47347bea416f9347b99e)
> 11-03 14:21:10.246     0     0 E DEBUG   : #06 pc 000000000001eacd  /sbin/magisk64 (BuildId: b05097c33460eef1651d47347bea416f9347b99e)
> 11-03 14:21:10.246     0     0 E DEBUG   : #07 pc 0000000000093c88  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: 082396c74061b06f8ce2a645b3a60e84)
> 11-03 14:21:10.322     0     0 I init    : Untracked pid 62 received signal 6
> 11-03 14:21:10.322     0     0 I init    : Service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)' (pid 60) exited with status 0 waiting took 0.101000 seconds
> 11-03 14:21:10.322     0     0 I init    : Sending signal 9 to service 'exec 10 (/sbin/magisk --auto-selinux --post-fs-data)' (pid 60) process group...
> 11-03 14:21:10.322     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 60 in 0ms
> ```

Nah it's still magiskd that crashes.

**Comment by nitanmarcel** [comment]
Can you please fix the conflicts so I can merge this?

**Comment by nitanmarcel** [comment]
Also use Closes #nr to automatically close your issue upon merging.

nr being the issue number at the end of the url

https://github.com/nitanmarcel/waydroid-magisk/issues/19

**Comment by EternalFlameIV** [comment]
As far as I can tell, installing `linux-xanmod-anbox` from ArchLinuxCN does not help the issue. I've also got a personal build of `linux-xanmod` that includes binder and auto-enables PSI, and the Magisk install fails with a near-identical log across both kernels. Please find a representative segment of logcat below:
`
12-08 10:56:02.826     0     0 I init    : starting service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)'...
12-08 10:56:02.827     0     0 E libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
12-08 10:56:02.827     0     0 E init    : createProcessGroup(0, 49) failed for service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)': Read-only file system
12-08 10:56:02.827     0     0 I init    : SVC_EXEC service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' pid 49 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
12-08 10:56:02.830     0     0 I init    : Service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 49) exited with status 1 waiting took 0.003000 seconds
12-08 10:56:02.830     0     0 I init    : Sending signal 9 to service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 49) process group...
12-08 10:56:02.830     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 49 in 0ms
12-08 10:56:02.830    37    37 E android.system.suspend@1.0-service: error opening /sys/power/wakeup_count: Read-only file system
12-08 10:56:02.830     0     0 I init    : starting service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)'...
12-08 10:56:02.830    37    37 E android.system.suspend@1.0-service: error opening /sys/power/state: Read-only file system
12-08 10:56:02.830    25    25 I Checkpoint: cp_prepareCheckpoint called
12-08 10:56:02.830    37    37 E cutils-trace: Error opening trace file: No such file or directory (2)
12-08 10:56:02.830    23    23 E cutils-trace: Error opening trace file: No such file or directory (2)
12-08 10:56:02.830    23    23 I hwservicemanager: getFrameworkHalManifest: Reading VINTF information.
12-08 10:56:02.830     0     0 I init    : SVC_EXEC service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' pid 50 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
12-08 10:56:02.832    23    23 I hwservicemanager: getFrameworkHalManifest: Successfully processed VINTF information
12-08 10:56:02.832    37    37 I HidlServiceManagement: Registered android.system.suspend@1.0::ISystemSuspend/default
12-08 10:56:02.832    37    37 I HidlServiceManagement: Removing namespace from process name android.system.suspend@1.0-service to suspend@1.0-service.
12-08 10:56:02.832     0     0 I init    : Service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 50) exited with status 1 waiting took 0.002000 seconds
12-08 10:56:02.832     0     0 I init    : Sending signal 9 to service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 50) process group...
`
...followed by the "su" command not existing upon `sudo waydroid_magisk setup`.

**Comment by EternalFlameIV** [comment]
Here are full logs taken while running `linux-xanmod-anbox`- the procedure I used to get them is as follows:
- run `waydroid show-full-ui`
- start logcat: `sudo waydroid logcat > ~/path/to/logcat-anbox.txt `
- fumble around with redirection operators because I'm not great at using them (or any other ~3 minute delay)
- after figuring out redirection, take `waydroid_magisk` log: `sudo python ./waydroid_magisk.py log &> ~/path/to/magisk-log-anbox.txt`
- shut down waydroid session; the logcat ends by itself
- make .txt files user-readable, upload
[logcat-anbox.txt](https://github.com/nitanmarcel/waydroid-magisk/files/13620737/logcat-anbox.txt)
[magisk-log-anbox.txt](https://github.com/nitanmarcel/waydroid-magisk/files/13620738/magisk-log-anbox.txt)

**Comment by DaRandomCube** [comment]
> Also use Closes #nr to automatically close your issue upon merging.
> 
> nr being the issue number at the end of the url
> 
> #19

idk how to fix conflicts
+
idk how to use closes #nr

**Comment by a7md8762** [comment]
> As far as I can tell, installing `linux-xanmod-anbox` from ArchLinuxCN does not help the issue. I've also got a personal build of `linux-xanmod` that includes binder and auto-enables PSI, and the Magisk install fails with a near-identical log across both kernels. Please find a representative segment of logcat below:
> 
> ```
> 12-08 10:56:02.826     0     0 I init    : starting service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)'...
> 12-08 10:56:02.827     0     0 E libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
> 12-08 10:56:02.827     0     0 E init    : createProcessGroup(0, 49) failed for service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)': Read-only file system
> 12-08 10:56:02.827     0     0 I init    : SVC_EXEC service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' pid 49 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
> 12-08 10:56:02.830     0     0 I init    : Service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 49) exited with status 1 waiting took 0.003000 seconds
> 12-08 10:56:02.830     0     0 I init    : Sending signal 9 to service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 49) process group...
> 12-08 10:56:02.830     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 49 in 0ms
> 12-08 10:56:02.830    37    37 E android.system.suspend@1.0-service: error opening /sys/power/wakeup_count: Read-only file system
> 12-08 10:56:02.830     0     0 I init    : starting service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)'...
> 12-08 10:56:02.830    37    37 E android.system.suspend@1.0-service: error opening /sys/power/state: Read-only file system
> 12-08 10:56:02.830    25    25 I Checkpoint: cp_prepareCheckpoint called
> 12-08 10:56:02.830    37    37 E cutils-trace: Error opening trace file: No such file or directory (2)
> 12-08 10:56:02.830    23    23 E cutils-trace: Error opening trace file: No such file or directory (2)
> 12-08 10:56:02.830    23    23 I hwservicemanager: getFrameworkHalManifest: Reading VINTF information.
> 12-08 10:56:02.830     0     0 I init    : SVC_EXEC service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' pid 50 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
> 12-08 10:56:02.832    23    23 I hwservicemanager: getFrameworkHalManifest: Successfully processed VINTF information
> 12-08 10:56:02.832    37    37 I HidlServiceManagement: Registered android.system.suspend@1.0::ISystemSuspend/default
> 12-08 10:56:02.832    37    37 I HidlServiceManagement: Removing namespace from process name android.system.suspend@1.0-service to suspend@1.0-service.
> 12-08 10:56:02.832     0     0 I init    : Service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 50) exited with status 1 waiting took 0.002000 seconds
> 12-08 10:56:02.832     0     0 I init    : Sending signal 9 to service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 50) process group...
> ```
> 
> ...followed by the "su" command not existing upon `sudo waydroid_magisk setup`.

Same here, I have `linux-xanmod-anbox` and `linux-xanmod-anbox-dkms` But when I run `sudo waydroid_magisk setup` It still gives This:
`lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "su"`

**Comment by nitanmarcel** [comment]
> > As far as I can tell, installing `linux-xanmod-anbox` from ArchLinuxCN does not help the issue. I've also got a personal build of `linux-xanmod` that includes binder and auto-enables PSI, and the Magisk install fails with a near-identical log across both kernels. Please find a representative segment of logcat below:
> > ```
> > 12-08 10:56:02.826     0     0 I init    : starting service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)'...
> > 12-08 10:56:02.827     0     0 E libprocessgroup: Failed to make and chown /acct/uid_0: Read-only file system
> > 12-08 10:56:02.827     0     0 E init    : createProcessGroup(0, 49) failed for service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)': Read-only file system
> > 12-08 10:56:02.827     0     0 I init    : SVC_EXEC service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' pid 49 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
> > 12-08 10:56:02.830     0     0 I init    : Service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 49) exited with status 1 waiting took 0.003000 seconds
> > 12-08 10:56:02.830     0     0 I init    : Sending signal 9 to service 'exec 8 (/system/etc/init/magisk/magisk64 --auto-selinux --setup-sbin /system/etc/init/magisk)' (pid 49) process group...
> > 12-08 10:56:02.830     0     0 I libprocessgroup: Successfully killed process cgroup uid 0 pid 49 in 0ms
> > 12-08 10:56:02.830    37    37 E android.system.suspend@1.0-service: error opening /sys/power/wakeup_count: Read-only file system
> > 12-08 10:56:02.830     0     0 I init    : starting service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)'...
> > 12-08 10:56:02.830    37    37 E android.system.suspend@1.0-service: error opening /sys/power/state: Read-only file system
> > 12-08 10:56:02.830    25    25 I Checkpoint: cp_prepareCheckpoint called
> > 12-08 10:56:02.830    37    37 E cutils-trace: Error opening trace file: No such file or directory (2)
> > 12-08 10:56:02.830    23    23 E cutils-trace: Error opening trace file: No such file or directory (2)
> > 12-08 10:56:02.830    23    23 I hwservicemanager: getFrameworkHalManifest: Reading VINTF information.
> > 12-08 10:56:02.830     0     0 I init    : SVC_EXEC service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' pid 50 (uid 0 gid 0+0 context u:r:su:s0) started; waiting...
> > 12-08 10:56:02.832    23    23 I hwservicemanager: getFrameworkHalManifest: Successfully processed VINTF information
> > 12-08 10:56:02.832    37    37 I HidlServiceManagement: Registered android.system.suspend@1.0::ISystemSuspend/default
> > 12-08 10:56:02.832    37    37 I HidlServiceManagement: Removing namespace from process name android.system.suspend@1.0-service to suspend@1.0-service.
> > 12-08 10:56:02.832     0     0 I init    : Service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 50) exited with status 1 waiting took 0.002000 seconds
> > 12-08 10:56:02.832     0     0 I init    : Sending signal 9 to service 'exec 9 (/system/etc/init/magisk/magiskpolicy --live --magisk allow * magisk_file lnk_file *)' (pid 50) process group...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...followed by the "su" command not existing upon `sudo waydroid_magisk setup`.
> 
> Same here, I have `linux-xanmod-anbox` and `linux-xanmod-anbox-dkms` running, But when I run `sudo waydroid_magisk setup` It still gives This: `lxc-attach: waydroid: ../src/lxc/attach.c: lxc_attach_run_command: 1841 No such file or directory - Failed to exec "su"`
> 
> It seems like the issue is from waydroid-magisk itself. If you could, can you provide the commands to setup Magisk Manually?

Could you send a full log? And open a new issue about this?

**Comment by DaRandomCube** [comment]
The project is on hold
Merging is useless now as magisk doesn't work anyway
I've forgot that such PR was even there

**Comment by nitanmarcel** [comment]
> The project is on hold Merging is useless now as magisk doesn't work anyway I've forgot that such PR was even there

https://github.com/nitanmarcel/waydroid-magisk/issues/31#issuecomment-2230082713

**Comment by nitanmarcel** [comment]
Tho it will take a while until I compile my own version of magisk. I'm planning to rewrite this project entirely

**Pull request merged**
